extends: ['eslint:recommended', 'prettier']

plugins: ['prettier']

env:
   browser: true
   node: true
   es6: true

rules:
   'prettier/prettier': 'error'
   camelcase: ['error']
   eqeqeq: ['error']

   parserOptions:
   sourcetype: 'module'
